export const dom = {
    themeRadioButtons: Array.from(document.querySelectorAll('.settings__item input[name="theme"]')),
    playerRadioButtons: Array.from(document.querySelectorAll('.settings__item input[name="player"]')),
    sizeRadioButtons: Array.from(document.querySelectorAll('.settings__item input[name="size"]')),
    settingsSummaryLabels: Array.from(document.querySelectorAll('.settings__summary-label')),
    settingsPreviewImg: document.querySelector<HTMLImageElement>('.settings__preview-image'),
    gameCards: document.querySelector('.game__cards'),
    hero: document.getElementById('hero'),
    heroButton: document.getElementById('hero-button'),
    settings: document.getElementById('settings'),
    settingsStartButton: document.getElementById('settings-start-button'),
    game: document.getElementById('game'),
    gameExitButton: document.getElementById('game-exit-button'),
    gameCurrentPlayerIcon: document.getElementById('game-current-player-icon') as HTMLImageElement,
    bluePoints: document.querySelector('.game__player-points-blue'),
    orangePoints: document.querySelector('.game__player-points-orange'),
    popup: document.getElementById('popup'),
    popupWindow: document.getElementById('popup-window'),
    popupBackButton: document.getElementById('popup-back-button'),
    popupExitButton: document.getElementById('popup-exit-button'),
};